site_name: KCLC official Homepage
site_url: https://kclc-kaisei.github.io/
repo_url: https://github.com/kclc-kaisei/kclc-kaisei.github.io/
repo_name: kclc-kaisei/kclc-kaisei.github.io
site_author: KCLC
site_description: >-
  KCLC official Homepage
theme:
  name: material
  # custom_dir: overrides
  language: ja
  favicon: assets/img/favicon.ico
  features:
    - navigation.tabs
  # palette:
  #   accent: cyan
  #   primary: cyan

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kclc-kaisei/kclc-kaisei.github.io
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/42ndKCLC

markdown_extensions:
  # extension for syntax highlight
  # - codehilite
  # - codehilite:
  #     linenums: true

  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  # - git-revision-date-localized

nav:
  - Home: index.md
  - Course:
    - 第0章-はじめに: articles/chapter0/index.md
    - 第1章-コードの実行: articles/chapter1/index.md
    - 第2章-C++の基礎文法: articles/chapter2/index.md
    - 第3章-役に立つリンク集: articles/chapter3/index.md

  - APG4b:
    - 1.00.はじめに: APG4b/1-0/index.md
    - 1.01.出力とコメント: APG4b/1-1/index.md
    - 1.02.プログラムの書き方とエラー: APG4b/1-2/index.md
    - 1.03.四則演算と優先順位: APG4b/1-3/index.md
    - 1.04.変数と型: APG4b/1-4/index.md
    - 1.05.実行順序と入力: APG4b/1-5/index.md
    - 1.06.if文・比較演算子・論理演算子: APG4b/1-6/index.md
    - 1.07.条件式の結果とbool型: APG4b/1-7/index.md
    - 1.08.変数のスコープ: APG4b/1-8/index.md
    - 1.09.複合代入演算子: APG4b/1-9/index.md
    - 1.10.while文: APG4b/1-10/index.md
    - 1.11.for文・break・continue: APG4b/1-11/index.md
    - 1.12.文字列と文字: APG4b/1-12/index.md
    - 1.13.配列: APG4b/1-13/index.md
    - 1.14.STLの関数: APG4b/1-14/index.md
    - 1.15.関数: APG4b/1-15/index.md